# Generated by Django 4.1.1 on 2022-10-04 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)')], default='밝히고 싶지 않음', max_length=1, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(default='', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')]),
        ),
    ]
